### PR TITLE
/service-info values for approved GA4GH APIs

### PR DESCRIPTION
**Pull request by jb-adams**
To address Issue #4 

Starting csv and json docs, which list approved GA4GH API-based standards. Each entry includes the required attributes and values to be used in the `/service-info` `type` field of the corresponding service type.

Questions for TASC:
- Are we interested in keeping the CSV OR the JSON file?
- Any missing API-based standards? (passports?)
- Any info to be added/corrected?

### CODE REVIEW

**Comment by jmarshall** [comment]
Neither refget nor htsget have incorporated (standard) service-info yet. So while the listed `artifact` values are likely the ones they'll propose, the `version` values are premature.

As this originates with the relevant working group and is then looked at and vetted by TASC (per https://github.com/ga4gh/TASC/issues/4#issue-553822827), it would be best not to list refget or htsget entries until they have been formalised and proposed by the respective work stream subgroups.

**Comment by rishidev** [comment]
@jb-adams Now the format has been confirmed please go ahead and adjust this PR accordingly

**Comment by jb-adams** [comment]
> @jb-adams Now the format has been confirmed please go ahead and adjust this PR accordingly

done, should I request review or are we ok to merge?

**Comment by jmarshall** [comment]
PR #11 as merged includes both JSON and TSV, so I'm not sure what the basis for removing TSV is?

My previous comment (https://github.com/ga4gh/TASC/pull/9#issuecomment-589832972) has not been addressed. Neither `refget` nor `htsget` currently implements service-info, so listing them here is premature — per the process just added, this is a job for LSG to raise a PR adding them to the list in due course, when the protocols implement it. This may well apply to some of the other items listed too.

**Comment by jb-adams** [comment]
When we first started work on this issue, we hadn't agreed upon what file format to use (JSON or TSV). The information is completely redundant so I removed TSV to avoid duplication. I can add it back in if TASC decides it's useful to have both formats.

Regarding the previous comment, to my knowledge only `service-registry` implements the `/service-info` endpoint according to the `service-info` specification. The current GA4GH APIs are planned to incorporate `service-info`, so I added them into this list. I can remove them if TASC agrees they shouldn't appear in the type list yet, to be added back in by each work stream.

**Comment by rishidev** [comment]
Thanks for clarifying the JSON only approach with the file. We can remove the htsget and refget items if the groups want to do that separately, but I believe the groups for the RNASeq and Cloud related APIs are expecting these entries to go through.

**Comment by jb-adams** [comment]
I removed `htsget` and `refget` service type objects from the JSON file, they will be added in later when the corresponding standards incorporate `service-info`. In the list we now have `beacon`, `service-registry`, `rnaget`, `drs`, `trs`, and `wes`

**Comment by rishidev** [comment]
Thanks - this looks good to merge now. We are happy from the subgroups involved with those names and has been looked at by the Discovery Networks group. Will merge 2020-05-01 UT if there are no objections raised.

**Comment by rishidev** [comment]
Thanks all for the input, now merging for the values indicated by @jb-adams

**Pull request merged**
